version: "3.7"

volumes:
  postgres-data:

services:
  db:
    image: postgres:11.2-alpine
    container_name: admiring-gamification-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env.docker
    container_name: admiring-gamification-app
    ports:
      - "4000:4000"
    depends_on:
      - db
